### ISSUE TITLE
telemetry_buffer_manager_example segfaults if compiled in release 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology-playground/yarp-telemetry#59]
When I run `./bin/telemetry_buffer_manager_example` I got the following segmentation fault 
```
File saved correctly!
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
```
```
gdb$ where
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6c51921 in __GI_abort () at abort.c:79
#2  0x00007ffff7a99257 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7aa4606 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7aa4671 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7aa4905 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7a9bb46 in std::__throw_out_of_range(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555558466 in std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, yarp::telemetry::Buffer<double> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, yarp::telemetry::Buffer<double> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::at (__k="one", this=0x7fffffffc730) at /usr/include/c++/7/bits/hashtable_policy.h:774
#8  std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, yarp::telemetry::Buffer<double>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, yarp::telemetry::Buffer<double> > > >::at (__k="one", this=0x7fffffffc730) at /usr/include/c++/7/bits/unordered_map.h:990
#9  yarp::telemetry::BufferManager<double>::push_back (var_name="one", elem=..., this=0x7fffffffc700) at /home/gromualdi/robot-code/yarp-telemetry/src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h:85
#10 main () at /home/gromualdi/robot-code/yarp-telemetry/src/examples/telemetry_buffer_manager_example.cpp:75
```

I think it's related to #57

**Comment by Nicogene** [comment]
The fix to this particular problem should be carried in #55
